name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          default: true

      - name: Build Binary
        run: cargo build --release

      - name: Download weight table
        run: wget https://poyo.me/reversi/table220710.tar.gz && tar xf table220710.tar.gz

      - name: Run Test
        run: cargo test --release

      - name: Run Benchmark
        run: cargo bench
